// <auto-generated />
using System;
using Mego.travel.Test_WebReport_Excel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mego.travel.Test_WebReport_Excel.Migrations
{
    [DbContext(typeof(OrderContext))]
    [Migration("20211122141602_OrdersTableCreate")]
    partial class OrdersTableCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mego.travel.Test_WebReport_Excel.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 10, 1, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 560
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 10, 5, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 550
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 10, 10, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 700
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 10, 18, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 710
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2021, 11, 25, 18, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 330
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2021, 11, 1, 8, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 1001
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2021, 11, 2, 9, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 2002
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2021, 11, 3, 10, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 2033
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2021, 11, 4, 11, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 2005
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2021, 11, 5, 12, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 3003
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2021, 11, 5, 13, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 4004
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2021, 11, 5, 14, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 3200
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2021, 11, 6, 15, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 4560
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2021, 11, 7, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 5000
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2021, 11, 8, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 4999
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2021, 11, 8, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 5500
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2021, 11, 8, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 6000
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2021, 11, 8, 16, 59, 59, 0, DateTimeKind.Unspecified),
                            Price = 6500
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
